Maquetado de header
santoyomontoyar/website-tercer-parcial pull request #19
Opened 2024-11-22 04:15 UTC by Luis-Alejandro-Ledesma

fixes #1

Este maquetado contiene:
- Logo
- menu interactivo
- Header sigue al scroll
<img width="1470" alt="Screenshot 2024-11-21 at 11 14 12 p m" src="https://github.com/user-attachments/assets/859cc3fe-e770-48dc-a4f4-bc06c3182a94">

2024-11-22 17:52 UTC, santoyomontoyar approved these changes
El código ya fue revisado, no se encontraron errores así que muy bien! revisión finalizada

2024-11-23 19:55 UTC, maoriab requested changes
No se está utilizando Bootstrap en este archivo.

2024-11-23 20:42 UTC, santoyomontoyar requested changes
solicito que revises la documentacion de boootstrap para ver si hay manera de realizar este maquetado usando bootstrap

2024-11-26 21:57 UTC, santoyomontoyar approved these changes
Revisado, el header ahora si se realizo usando bootstrap, contiene lo solicitado

2024-11-26 22:00 UTC, maoriab approved these changes
Revisado, se hicieron los cambios solicitados, al parecer no hay errores.

2024-11-26 22:01 UTC, merged