maquetado de Any questions 2
santoyomontoyar/website-tercer-parcial pull request #40
Opened 2024-11-30 19:59 UTC by alexx-canul

titulo
Imágenes de trabajos
las imágenes se deslizan hacia un lado como tipo carrusel
<img width="1314" alt="Captura de pantalla 2024-11-30 a la(s) 14 57 01" src="https://github.com/user-attachments/assets/410a685b-e2f1-48a9-85ca-41ad9caaf3e6">

2024-11-30 20:01 UTC, alexx-canul commented
el nombre esta maal, jajaja, es our-work :c

2024-12-01 06:04 UTC, santoyomontoyar requested changes
código en revisión, hay algunos detalles, trata de eliminar los nombres que aparecen en las flechas al igual tratar que dichas flechas de parezcan mas a las del figma, además si es posible, los puntos que nos indican en que foto estamos ya sea hacerlos parecidos al figma y aparte bajarlos sacándolos de la imagen, anexo foto                                                                  

![image](https://github.com/user-attachments/assets/76edf511-94be-48f9-ac67-7ebc5e11771e)

2024-12-02 02:19 UTC, alexx-canul commented
corregido 
<img width="1440" alt="Captura de pantalla 2024-12-01 a la(s) 21 14 16" src="https://github.com/user-attachments/assets/69ee01a1-6a2c-4fca-a8cd-b3785d007354">

2024-12-02 21:51 UTC, maoriab approved these changes
revisado, no se encontraron errores

2024-12-02 21:53 UTC, santoyomontoyar approved these changes
cambios hechos, código revisado

2024-12-02 21:53 UTC, merged